config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todolists
  get 'home/about'
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todolist.rb
class Todolist < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: %i[ show edit update destroy ]

  # GET /todolists or /todolists.json
  def index
    @todolists = Todolist.all
  end

  # GET /todolists/1 or /todolists/1.json
  def show
  end

  # GET /todolists/new
  def new
    @todolist = Todolist.new
  end

  # GET /todolists/1/edit
  def edit
  end

  # POST /todolists or /todolists.json
  def create
    @todolist = Todolist.new(todolist_params)

    respond_to do |format|
      if @todolist.save
        format.html { redirect_to todolist_url(@todolist), notice: "Todolist was successfully created." }
        format.json { render :show, status: :created, location: @todolist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todolists/1 or /todolists/1.json
  def update
    respond_to do |format|
      if @todolist.update(todolist_params)
        format.html { redirect_to todolist_url(@todolist), notice: "Todolist was successfully updated." }
        format.json { render :show, status: :ok, location: @todolist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todolist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todolists/1 or /todolists/1.json
  def destroy
    @todolist.destroy

    respond_to do |format|
      format.html { redirect_to todolists_url, notice: "Todolist was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todolist
      @todolist = Todolist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todolist_params
      params.require(:todolist).permit(:Tasks, :Priority, :Urgency, :Active, :Category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<! creating route for the path >
<%= link_to 'Todo App', root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if user_signed_in? %>
      <li class="nav-item">
      <li class="nav-item">
      <%= link_to 'View', todolists_path, class:"nav-link"%>
      </li>
      <%= link_to 'AddTask', new_todolist_path, class:"nav-link"%>
      </li>
    
      <li class="nav-item">
      <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
    </li>


      <li class="nav-item">
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:" text-danger btn btn-light" %>
      </li>
    
    <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
      </li>
    <% end %>
    <li class="nav-item">
    <%= link_to 'About', home_about_path, class:"nav-link"%>
  </li>
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Hello There :D</h1>
    <p class="lead">This is my first app built using ruby on rails. There are a lot of improvements to be made and I will try to make it.</p>
  </div>
</div>

app/views/home/index.html.erb
<h1>Hello there! </h1>
This is my first webapp for todo list. Feel free to use it.

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert"><%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>TodoApps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render 'home/header'%>
  <div class="container">
   <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
  <%= yield %>
  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/todolists/_form.html.erb
<%= form_with(model: todolist) do |form| %>
  <% if todolist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todolist.errors.count, "error") %> prohibited this todolist from being saved:</h2>

      <ul>
        <% todolist.errors.full_message.each do |message| %>
          <li><%=message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
  <div class="field form-group"
    <%= form.label :Tasks, style: "display: block" %>
    <%= form.text_field :Tasks, class:"form-control", placeholder:"Description" %>
  </div>

  <div class="field form-group"
    <%= form.label :Priority, style: "display: block" %>
    <%= form.text_field :Priority, class:"form-control", placeholder:"High Low Medium" %>
  </div>

  <div class="field form-group"
    <%= form.label :Urgency, style: "display: block" %>
    <%= form.number_field :Urgency, class:"form-control", placeholder:"1-5" %>
  </div>

  <div class="field form-group"
    <%= form.label :Active, style: "display: block" %>
    <%= form.check_box :Status %>
  </div>

  <div class="field form-group"
    <%= form.label :Category, style: "display: block" %>
    <%= form.text_field :Category, class:"form-control" %>
  </div>

  <div>
    <%= form.submit class:'btn btn-secondary'%>
  </div>
<% end %>

app/views/todolists/_todolist.html.erb
<div id="<%= dom_id todolist %>">
  <p>
    <strong>Tasks:</strong>
    <%= todolist.Tasks %>
  </p>

  <p>
    <strong>Priority:</strong>
    <%= todolist.Priority %>
  </p>

  <p>
    <strong>Urgency:</strong>
    <%= todolist.Urgency %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= todolist.Active %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= todolist.Category %>
  </p>

</div>

app/views/todolists/edit.html.erb
<h1>Edit</h1>

<%= render "form", todolist: @todolist %>
<br>
<div>
  <%= link_to "Back", todolists_path, class:"btn btn-secondary" %>
</div>

app/views/todolists/index.html.erb
<table class="table table-striped table-hover" >
  <thead class="thead-dark">
  <tr>
    <th>Tasks</th>
    <th>Priority</th>
    <th>Urgency</th>
    <th>Active</th>
    <th>Category</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <tr>
  <% @todolists.each do |todolist| %>
  <td><%= todolist.Tasks %> </td>
  <td><%= todolist.Priority %> </td>
  <td><%= todolist.Urgency %> </td>
  <td><%= todolist.Active %> </td>
  <td><%= todolist.Category%> </td>

  <td><%= link_to 'Show', todolist_path(todolist) %></td>
  <td><%= link_to 'Edit', edit_todolist_path(todolist)%></td>
  <td><%= link_to 'Done', todolist, method: :delete%>
  </tr>
  <% end %>

  </table>
<%= link_to "Add Task", new_todolist_path, class: "btn btn-secondary" %>

app/views/todolists/new.html.erb
<h1>Add Task</h1>
<br/>
<%= render "form", todolist: @todolist %>
<div>
<br>
  <%= link_to "Back ", todolists_path, class:"btn btn-secondary"%>
</div>

app/views/todolists/show.html.erb
<div class="jumbotron">
<h1 class="display-4">Hello there!</h1>
<p class="lead">Here is the detail of your task.</p>
<hr class="my-4">
<%= render @todolist %>
<%= link_to "Edit", edit_todolist_path(@todolist), class:"btn btn-secondary" %> 
<%= link_to "Back ", todolists_path, class:"btn btn-secondary" %>
<br>
<br>
<%= button_to "Remove", @todolist, method: :delete, class:"btn btn-danger" %>
</div>